---
title: "Explore compensation data"
author: "Mikyas Duga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE)


library(readr)
library(dplyr)
library(data.table)
library(dtplyr)
library(collapse)
library(stringr)

```


```{r}
## some are compensated at reporting organization and also a related organization(s). 


df_comp <- read_rds("data/df_comp.rds") %>% 
  fmutate(across(c("avg_hrs", "rep_comp", "rep_comp_rltd"), 
                 as.numeric)) %>% 
  fsubset(avg_hrs >= 1 & ## select those who have worked at least 1 hr per week and
           rep_comp >=1000)  ## paid more than $1000/year by the reporting organization  


upper_squish <- function(z){
  
  z <- toupper(str_squish(z))
}


df_comp2 <- df_comp %>% 
  fmutate(Org_name = toupper(Org_name),
         org_type = if_else(Return_type == "990", "PC", "PF"),
         Tax_yr = as.numeric(Tax_yr), 
         Tax_period = lubridate::date(Tax_yr_end) - 
           lubridate::date(Tax_yr_begin), 
         comb_501c = case_when(
           Organization501c3Ind == "X" | ind_501c3 == 'X' ~ '501c3', 
           ind_501c == 'X' ~ paste0('501c', type_501c), 
           TRUE ~ NA 
         ), 
         zip_code = if_else(str_length(zip_code) == 9, 
                            paste(substr(zip_code, 1, 5),
                                  substr(zip_code, 6, 9),
                                  sep = "-"), 
                            zip_code), 
         GroupReturnForAffiliatesInd = if_else((GroupReturnForAffiliatesInd == 'false'), 
                                              '0', GroupReturnForAffiliatesInd), 
         GroupReturnForAffiliatesInd = if_else((GroupReturnForAffiliatesInd == 'true'), 
                                               '1', GroupReturnForAffiliatesInd),
         FormationYr = as.numeric(FormationYr)) %>% 
  fmutate(across(c("CY_expenses", "assets_eoy", "total_employee_cnt", 
              "avg_hrs_rltd", "other_comp", "ben_program_amt", 
              "other_allwnc_amt"), as.numeric)) %>% 
  fmutate(across(where(is.character), upper_squish)) %>% 
  fselect(-c(5:9, 18, 19, 32)) %>%  ## drop extraneous variables. not helpful for analysis. 
  fsubset(!is.na(names))  ## drop rows with no names


# df_comp2 <- df_comp2 %>% 
#   mutate(flag_dup = duplicated(.))
# 
# 
# dupes <- df_comp2 %>% 
#    filter(flag_dup == TRUE)  ## there are some duplicates and some times errors. 

df_comp2 <- df_comp2 %>%
  mutate(id = paste(EIN, names, sep = "-")) %>% 
  group_by(id) %>% 
  arrange(avg_hrs) %>% 
  distinct() %>% 
  ungroup()


# df_comp2 <- df_comp2 %>% 
#   mutate(flag_dup2 = duplicated(.))

# 
# dupes2 <- df_comp2 %>%
#    filter(flag_dup2 == TRUE)  ## no duplicates



```

## CLEAN UP TITLES

```{r}

## clean up titles. borrowed from other project. 

ed_titles <- c("CEO", "CHIEF EXECUTIVE OFFICER", 
               "EXEC DI", "EXECUTIVE DI", "EXEC. DIR", 
               "EXECUTIVE DIREC", 
              "EXECUTIVE DIR", "EXECUTIVEDIRECTO", "EXEC DIR", 
              "EX DIRECTOR")



pres_and_ed <- c("PRESIDENT &", "PRESIDENT AND", "PRESIDENT/", 
                 "PRESIDENT, EXEC")




df_comp2 <- df_comp2 %>%
  frename(title = titles) %>% 
  fsubset(!is.na(title)) %>% 
  fmutate(
    title = str_squish(title),
    title = str_replace_all(title, "///", " AND "),  ## replace '/' with ' and '
    title = str_remove_all(title, "[//.]"),
    title = str_replace_all(title, ",", "AND"),
    title = str_replace_all(title, "&", "AND"),
  title = str_replace_all(title, "VP", "VICE PRESIDENT"),
  title = str_replace_all(title, "VICE-PRESIDENT", "VICE PRESIDENT"),
  title = if_else((str_detect(title, "COORDINATOR") == FALSE), 
                  str_remove_all(title, "CO "),
                  title), ## remove co from title of co-leaders
  title = if_else((str_detect(title, "COORDINATOR") == FALSE),  ## if title doesn't include coordinator remove co-
                  str_remove_all(title, "CO-"), title),
  title = str_replace_all(title, " - ", " "), ## typically used to provide description. VP - x program
  title = str_replace_all(title, "-", ""),
  title = str_replace_all(title, "SR ", "SENIOR " ),
  title = if_else(title == "RN", "REGISTERED NURSE", title), 
  title = str_replace_all(title, "IT ", "INFROMATION TECHNOLOGY "),
  title = str_replace_all(title, "HR ", "HUMAN RESOURCES "),
  title = str_replace_all(title, "CEO", "EXECUTIVE DIRECTOR"),
 
  title = str_replace_all(title, "CFO", "CHIEF FINANCIAL OFFICER"),
  title = str_replace_all(title, "COO", "CHIEF OPERATING OFFICER"),
  title = str_replace_all(title, "CIO", "CHIEF INFORMATION OFFICER"),
  title = str_replace_all(title, "CMO", "CHIEF MEDICAL OFFICER"),
  # title = str_replace_all(title, "CAO", "CHIEF ADMINISTRATIVE OFFICER"),  ## COULD BE ACADEMIC/ADVANCEMENT OFFIER
  title = str_replace_all(title , "CDO", "CHIEF DEVELOPMENT OFFICER"),
  title = str_replace_all(title , "CPO", "CHIEF PEOPLE OFFICER"),
  title = str_replace_all(title , "CBO", "CHIEF BUSINESS OFFICER"),
  title = str_replace_all(title , "CNO", "CHIEF NURSING OFFICER"),
  title = str_replace_all(title, "HR", "HUMAN RESOURCES"),
  title = str_replace_all(title, "MGR", "MANAGER"),
  title = if_else(title  == "1ST VICE PRE" |
                         title ==  "1ST VP", "1ST VICE PRESIDENT", title),
  title = if_else(str_starts(title, "2ND VICE PRE"), "2ND VICE PRESIDENT", title),
  title = if_else(str_starts(title, "ADMINIST"), "ADMINISTRATOR", title),
  title = if_else(title  %in% ed_titles, "EXECUTIVE DIRECTOR", title),

  title = if_else(str_starts(title, "EXEC BO"), "EXECUTIVE BOARD OFFICER", title),
  # title = if_else(title %in% pres_and_ed, "PRESIDENT & CEO", title),
  title = if_else(str_starts(title, "VICE PRESIDE"), "VICE PRESIDENT", title),
  title = if_else(str_starts(title, "EXECUTIVE BO"), "EXECUTIVE BOARD OFFICER", title),
  title = if_else(str_starts(title, "ASSISTANT DI"), "ASSISTANT DIRECTOR", title),
  
  title = if_else(str_ends(title, "DIR"), str_replace(title, "DIR", "DIRECTOR"), title),
  title = if_else(str_ends(title, "DIRE"), str_replace(title, "DIRE", "DIRECTOR"), title),
  
  title = if_else(str_starts(title, "BOARD MAN"), "BOARD MANAGER", title),
  
  title = if_else(str_starts(title, "BUSINESS MAN"), "BUSINESS MANAGER", title),
 

  title = if_else(str_starts(title, "EXECUTIVE COMM"), "EXECUTIVE COMMITTEE MEMBER", title),
  
  title = if_else(str_starts(title, "FINANCE OFF"), "FINANCE OFFICER", title),
  title = if_else(str_starts(title, "FINANCIAL SE"), "FINANCIAL SECRETARY", title),
  title = if_else(str_starts(title, "HEAD OF SCHO"), "HEAD OF SCHOOL", title),
  
  title = str_replace_all(title, "PAST", "FORMER"),
 
  title = if_else(str_starts(title, "SUPERINTENDE"), "SUPERINTENDENT", title),
  title = if_else(str_starts(title, "SVICE P"), "SENIOR VICE PRESIDENT", title),
  title = if_else(str_starts(title, "VICE PRES"), "VICE PRESIDENT", title),
  title = if_else(str_starts(title, "CHIEF OPERATING OFF"), "CHIEF OPERATIONS OFFICER", title),
  title = if_else(title == "DIRECTOR OF", "DIRECTOR", title),
  title = if_else(str_starts(title, "EX. BOARD"), "EXECUTIVE BOARD MEMBER", title),
  title = str_replace_all(title, "PRIOR", "FORMER"),
  title = if_else(str_detect(title, "SEE SCHEDULE O"), NA, title))





# DT::datatable(df_comp2 %>% 
#                 fselect(title) %>% 
#                 fcount(title, sort = TRUE))




df_comp3 <- df_comp2 %>% 
  fsubset(!is.na(title)) %>% 
  fmutate(title = str_squish(title),
         title = str_replace_all(title, "EXEC ","EXECUTIVE "), 
         title = str_replace_all(title, "DIR ", "DIRECTOR"),
         title = str_replace_all(title, "OPERATIONS OFFICER", "OPERATING OFFICER"),
         title = str_replace_all(title, "SGT", toupper("Sergeant")), 
         title = str_replace_all(title, " OF ", " ")) %>% ## change director of x to director x 
  fmutate(title = if_else(str_like(title, "DIRECTOR%"), ## change director x to x director. 
                         paste(paste0(str_remove(title, "DIRECTOR")), 
                         paste0("DIRECTOR")), 
                         title
                         ), ## adds an extra space in some cases
          title = str_squish(title),
          title = if_else((title == "PRESIDENTCEO"|
                            title == "PRESIDENTCE"), "PRESIDENT AND CEO", 
                          title ), 
          title = if_else((title == "MD" |
                            title == "MEDICAL DOCTOR"), "PHYSICIAN", title) , 
          title = if_else(str_ends(title, "DIR"), str_replace(title, "DIR", "DIRECTOR"), title),
          # title = if_else(title == "EXECUTIVE DIR", "EXECUTIVE DIRECTOR", title),
          
          title = if_else((title == "SECRETARY TREASURER" |
                            title == "SECRETARY TR" |
                             title == "SECRETARYTR" |
                             title == "TREASURERSECRETARY" |
                             title == "SEC TREASURER" |
                             title == "SECTREASURER" |
                             title == "SECRETARYTREASURER"), "SECRETARY AND TREASURER", title), 
          title = if_else(title == "GENERAL MANA", "GENERAL MANAGER", title), 
          title = if_else((title == "PRESIDENT CEO" |
                            title == "CEO AND PRESIDENT"), "PRESIDENT AND CEO", title), 
          title = if_else((title == "EXECUTIVE DIRECTO" |
                            title == "EXECUTIVE DIRECT"), "EXECUTIVE DIRECTOR", title), 
          title = if_else(title == "EXECUTIVE DIRECTORCEO", "EXECUTIVE DIRECTOR", title), 
          title = if_else(str_detect(title, "CHIEF EXECUTIVE OFFICER") &
                            !str_detect(title, "AND"), "EXECUTIVE DIRECTOR", 
                          title), 
          title = if_else(str_detect(title, "CHIEF EXECUTIVE OFFICER") &
                            str_detect(title, "PRESIDENT"), "PRESIDENT AND CEO", 
                          title) , 
          title = str_replace_all(title, "SARGENT", "SERGEANT"), ## fix spelling error
          title = str_replace_all(title, "SERGEANT ARMS", "SERGEANT AT ARMS"), 
          title = str_replace_all(title, "PRESIDENTDIRECTOR", "PRESIDENT AND DIRECTOR"), 
          title = if_else((title == "PRESIDENTEXECUTIVE DIRECTOR" |
                            title == "CEOPRESIDENT" |
                             title == "PRESIDENT AND EXECUTIVE DIRECTOR" |
                             title == "PRESIDENTAND CEO" |
                             title == "PRESIDENTAND EXECUTIVE DIRECTOR"|
                             title == "PRESIDENT EXECUTIVE DIRECTOR"|
                             title == "EXECUTIVE DIRECTORPRESIDENT" |
                             title == "EXECUTIVE DIRECTOR AND PRESIDENT"), "PRESIDENT AND CEO", title), 
          title = if_else((title == "CEOEXECUTIVEDIRECTOR" |
                                    title == "CEO" |
                             title == "EXECUTIVE DIRECTOREXECUTIVE DIRECTOR" |
                             title == "EXECUTIVE DIRE"), "EXECUTIVE DIRECTOR", title),
           title = str_replace_all(title, "BOARD DIRECTORS", "BOARD MEMBER"),
          title = if_else(title == "DEPUTY DIREC", "DEPUTY DIRECTOR", title), 
          title = if_else(title == "CHIEF FINANCIAL OFFICERCHIEF OPERATING OFFICER" |
                            title == "CHIEF FINANCIAL AND OPERATING OFFICER",
                          "CHIEF FINANCIAL OFFICER AND CHIEF OPERATING OFFICER", title),
          
          title = str_remove_all(title, "OF ")) %>% 
  fmutate(title = str_squish(title)) %>% 
  fsubset(title != "EMPLOYEE" &
            title != "KEY EMPLOYEE" &
            title != "KEY WORKER" &
            title != "SEE SCHEDULE O O AND T TITLES") %>%  ## REMOVE GENERIC TITLES WITH NO VALUE
  fsubset(str_detect(title, "FORMER") == FALSE &
            str_detect(title, "THRU") == FALSE &
            str_detect(title, "THROUGH") == FALSE &
            str_detect(title, "PART YEAR") ==  FALSE) %>%  ##EXCLUDE THOSE WHO SERVED ONLY FOR PART OF THE YEAR
  fmutate(title = if_else(str_ends(title, " AND") , 
                          str_remove(title, " AND"), title),  ## remove 'and' from the end of a title
          title = if_else(str_ends(title, " AN"), 
                          str_remove(title, " AN"), title),
          title = str_squish(title), 
          title = case_when(
            title == 'HEAD SCHOOL' ~ 'HEAD OF SCHOOL', ## add 'of' if necessary
            title == 'CHIEF STAFF' ~ 'CHIEF OF STAFF', 
            TRUE ~ title
          ), 
          title = if_else(title == "IT DIRECTOR", "INFORMATION TECHNOLOGY DIRECTOR", title), 
          title = if_else(title == "BUSINESS AGE", "BUSINESS AGENT", title), 
          title = if_else(title == "PRESIDENT DIRECTOR", "PRESIDNET AND DIRECTOR", title), 
          title = if_else(title == "PRESIDENTTREASURER", "PRESIDENT AND TREASURER", title), 
          title = if_else(title == "CHIEF FINANC", "CHIEF FINANCIAL OFFICER", title), 
          title = str_replace_all(title, "VICEPRESI", "VICE PRESIDENT"), 
          title = str_replace_all(title, "CHIEF FINANCIAL OFFICERTREASURER", 
                                  "CHIEF FINANCIAL OFFICER AND TREASURER"), 
          title = str_replace_all(title, "SERGEANTATARMS", "SERGEANT AT ARMS"), 
          title = str_replace_all(title, "CHAIRMAN", "CHAIR"), 
          title = str_replace_all(title, "CHAIRPERSON", "CHAIR"),
          title = str_replace_all(title, "VICECHAIR", "VICE CHAIR"),
          title = str_replace_all(title, "THE BOARD", "BOARD"),
          title = if_else(title == "CHAIR", "BOARD CHAIR", title), 
          title = if_else(title == "RECORDING SEC", "RECORDING SECRETARY", title),
          title = if_else(title == "BOARD DIRECTOR", "BOARD MEMBER", title), 
          title = str_remove(title, "STAFF "),
          title = str_squish(title))

         
temp_tbl <- df_comp3 %>% 
                fselect(title) %>% 
                fgroup_by(title) %>%
                fcount(title) %>% 
                fungroup() %>% 
                arrange(desc(N))



DT::datatable(temp_tbl)
                
## done -- VERIFY cOOCFO CFOCOO SITUATION!!!!!!##******** 

## sergeant at arms misspelled at times (fix sargent and sargent arms)
## presidentdirector to president/Director 
## ceopresident to president and ceo
## presidentexecutive director to president and ceo
## ceoexecutivedirector to executive director
## of finance director to finance director
## CEO to exec director
## board directors to BM
## deputy direc to deputy director 
## treasurersecretary and sec treasurer to secretary and treasurer or equivalent. ## check!!
## Coocfo, cfocoo, coo and cfo to CFO and coo
## SR to senior



## information technology director to IT director 
## head school to head of school & chief staff to chief of staff


```

## finish clean up 

```{r}
rm(df_comp, df_comp2)


## add irs bmf files


bmf_24 <- rbind(
  fread("data/eo1.csv"), 
  fread("data/eo2.csv"), 
  fread("data/eo3.csv"), 
  fread("data/eo4.csv")
  
)


bmf_24 <- bmf_24 %>% 
  janitor::clean_names() %>% 
  fmutate(ein = as.character(ein), 
          ein = str_pad(ein, width = 9 ,
                        side = "left", pad = "0")) %>% 
  fselect(ein, name, street, city, state, zip, 
          subsection, ntee_cd) ## just need the ntee code here. can drop id variables later. 



df_final <- df_comp3 %>% 
  janitor::clean_names() %>% 
  left_join(bmf_24, by = "ein") %>% 
  fmutate(ntee_cd = na_if(ntee_cd, "")) %>%    ## some orgs don't have ntee-cd classification even if they were matched with IRS data. 
  select(!(ends_with(".y"))) %>%
  fselect(-c(zip, street, name)) %>% 
  frename(city = city.x, 
          state = state.x)
  
rm(bmf_24)

fst::write_fst(df_final, path = "data/final_comp.fst")









```

