---
title: "Explore compensation data"
author: "Mikyas Duga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, 
                      message = FALSE)


library(readr)
library(dplyr)
library(data.table)
library(dtplyr)
library(collapse)
library(stringr)

```


```{r}
## some are compensated at reporting organization and also a related organization(s). 


df_comp <- read_rds("data/df_comp.rds") %>% 
  fmutate(across(c("avg_hrs", "rep_comp", "rep_comp_rltd"), 
                 as.numeric)) %>% 
  fsubset(avg_hrs > 0 &  ## select those who have worked more than 0 hrs
           rep_comp > 0)  ## paid at the reporting organization  


upper_squish <- function(z){
  
  z <- toupper(str_squish(z))
}


df_comp2 <- df_comp %>% 
  fmutate(Org_name = toupper(Org_name),
         org_type = if_else(Return_type == "990", "PC", "PF"),
         Tax_yr = as.numeric(Tax_yr), 
         Tax_period = lubridate::date(Tax_yr_end) - 
           lubridate::date(Tax_yr_begin), 
         comb_501c = case_when(
           Organization501c3Ind == "X" | ind_501c3 == 'X' ~ '501c3', 
           ind_501c == 'X' ~ paste0('501c', type_501c), 
           TRUE ~ NA 
         ), 
         zip_code = if_else(str_length(zip_code) == 9, 
                            paste(substr(zip_code, 1, 5),
                                  substr(zip_code, 6, 9),
                                  sep = "-"), 
                            zip_code), 
         GroupReturnForAffiliatesInd = if_else((GroupReturnForAffiliatesInd == 'false'), 
                                              '0', GroupReturnForAffiliatesInd), 
         GroupReturnForAffiliatesInd = if_else((GroupReturnForAffiliatesInd == 'true'), 
                                               '1', GroupReturnForAffiliatesInd),
         FormationYr = as.numeric(FormationYr)) %>% 
  fmutate(across(c("CY_expenses", "assets_eoy", "total_employee_cnt", 
              "avg_hrs_rltd", "other_comp", "ben_program_amt", 
              "other_allwnc_amt"), as.numeric)) %>% 
  fmutate(across(where(is.character), upper_squish)) %>% 
  fselect(-c(5:9, 18, 19, 32)) %>%  ## drop extraneous variables. not helpful for analysis. 
  fsubset(!is.na(names))  ## drop rows with no names


# df_comp2 <- df_comp2 %>% 
#   mutate(flag_dup = duplicated(.))
# 
# 
# dupes <- df_comp2 %>% 
#    filter(flag_dup == TRUE)  ## there are some duplicates and some times errors. 

df_comp2 <- df_comp2 %>%
  mutate(id = paste(EIN, names, sep = "-")) %>% 
  group_by(id) %>% 
  arrange(avg_hrs) %>% 
  distinct() %>% 
  ungroup()


# df_comp2 <- df_comp2 %>% 
#   mutate(flag_dup2 = duplicated(.))

# 
# dupes2 <- df_comp2 %>%
#    filter(flag_dup2 == TRUE)  ## no duplicates



```

## CLEAN UP TITLES

```{r}

## clean up titles. borrowed from other project. 

brd_mem_titles <- c("BOARD MEMBER", "TREASURER", "SECRETARY", "BOARD",
                   "SECRETARY/TREASURER", "BOARD CHAIR", "VICE CHAIR",
                   "CHAIRMAN", "CHAIRPERSON", "BOARD TREASURER",
                   "BOARD SECRETARY", "MEMBER", "RECORDING SE", 
                   "RECORDING SECRETARY", "SECRETARY/TR", "SECRETARY TREASURER", 
                   "CHAIR", "SEC/TREAS", "VICE CHAIRMA"
                   )

ed_titles <- c("CEO", "CHIEF EXECUTIVE OFFICER", 
               "EXEC DI", "EXECUTIVE DI", "EXEC. DIR", 
               "EXECUTIVE DIREC", 
              "EXECUTIVE DIR", "EXECUTIVEDIRECTO", "EXEC DIR")



pres_and_ed <- c("PRESIDENT &", "PRESIDENT AND", "PRESIDENT/", 
                 "PRESIDENT, EXEC")




df_comp2 <- df_comp2 %>%
  frename(title = titles) %>% 
  fmutate(title = if_else(title  %in% brd_mem_titles, "BOARD MEMBER", title),
  # fmutate(title = if_else(title  == "DIRECTOR", "EXECUTIVE DIRECTOR", title),
  title = str_replace_all(title, "-", " "),
  title = str_replace_all(title, "VP", "VICE PRESIDENT"),
  title = if_else(title  == "1ST VICE PRE" |
                         title ==  "1ST VP", "1ST VICE PRESIDENT", title),
  title = if_else(str_starts(title, "2ND VICE PRE"), "2ND VICE PRESIDENT", title),
  title = if_else(str_starts(title, "ADMINIST"), "ADMINISTRATOR", title),
  title = if_else(title  %in% ed_titles, "EXECUTIVE DIRECTOR", title),
  title = if_else(title  == "CFO", "CHIEF FINANCIAL OFFICER", title),
  title = if_else(title  == "COO", "CHIEF OPERATING OFFICER", title),
  title = if_else(str_starts(title, "EXEC BO"), "EXECUTIVE BOARD MEMBER", title),
  title = if_else(title %in% pres_and_ed, "PRESIDENT & CEO", title),
  title = if_else(str_starts(title, "VICE PRESIDE"), "VICE PRESIDENT", title),
  title = if_else(str_starts(title, "EXECUTIVE BO"), "EXECUTIVE BOARD MEMBER", title),
  title = if_else(str_starts(title, "ASSISTANT DI"), "ASSISTANT DIRECTOR", title),
  title = if_else(str_starts(title, "ASST DIRE"), "ASSISTANT DIRECTOR", title),
  title = if_else(str_starts(title, "BOARD MAN"), "BOARD MANAGER", title),
  title = if_else(str_starts(title, "CAO"), "CHIEF ADMINISTRATIVE OFFICER", title),
  title = if_else(str_starts(title, "BUSINESS MAN"), "BUSINESS MANAGER", title),
  title = if_else(str_starts(title, "CIO"), "CHIEF INFORMATION OFFICER", title),
  title = if_else(str_starts(title, "CMO"), "CHIEF MEDICAL OFFICER", title),
  title = str_remove_all(title, "CO "),
  title = if_else(str_starts(title, "EXECUTIVE COMM"), "EXECUTIVE COMMITTEE MEMBER", title),
  title = if_else(str_starts(title, "FINANCE DIRE"), "FINANCE DIRECTOR", title),
  title = if_else(str_starts(title, "FINANCE OFF"), "FINANCE OFFICER", title),
  title = if_else(str_starts(title, "FINANCIAL SE"), "FINANCIAL SECRETARY", title),
  title = if_else(str_starts(title, "HEAD OF SCHO"), "HEAD OF SCHOOL", title),
  title = if_else(str_starts(title, "MEDICAL DIRE"), "MEDICAL DIRECTOR", title),
  title = str_replace_all(title, "PAST", "FORMER"),
  title = if_else(str_starts(title, "PROGRAM DIRE"), "PROGRAM DIRECTOR", title),
  title = if_else(str_starts(title, "RN"), "REGISTERED NURSE", title),
  title = if_else(str_starts(title, "SUPERINTENDE"), "SUPERINTENDENT", title),
  title = if_else(str_starts(title, "SVICE P"), "SENIOR VICE PRESIDENT", title),
  title = if_else(str_starts(title, "VICE PRES"), "VICE PRESIDENT", title),
  title = if_else(str_starts(title, "ARTISTIC DIR"), "ARTISTIC DIRECTOR", title),
  title = if_else(str_starts(title, "CFO/TREAS"), "CHIEF FINANCIAL OFFICER", title),
  title = if_else(str_starts(title, "CHIEF OPERATING OFF"), "CHIEF OPERATIONS OFFICER", title),
  title = if_else(title == "DIRECTOR OF", "DIRECTOR", title),
  title = if_else(str_starts(title, "EX. BOARD"), "EXECUTIVE BOARD MEMBER", title),
  title = if_else(title == "FORMEROR", "PASTOR", title), #fix error from earlier step
  title = if_else(str_starts(title, "HR DIRECTOR"), "DIRECTOR OF HUMAN RESOURCES", title),
  title = str_replace_all(title, "PRIOR", "FORMER"),
  title = if_else(title == "SEE SCHEDULE O", NA, title))





DT::datatable(df_comp2 %>% 
                fselect(title) %>% 
                fcount(title, sort = TRUE))




df_comp3 <- df_comp2 %>% 
  fsubset(!is.na(title)) %>% 
  fmutate(title = str_replace_all(title, "///", " AND "),
          title = str_remove_all(title, "[//.,]"),
         title = str_replace_all(title, "DIRECTOR OF", "DIRECTOR"), 
         # title = str_replace_all(title, "DIR.", "DIRECTOR"), 
         title = str_replace_all(title, "&", "AND"), 
         title = str_replace_all(title, "///", "AND"),
         title = str_replace_all(title, "EXEC ","EXECUTIVE "), 
         title = str_replace_all(title, "DIR ", "DIRECTOR"),
         title = str_replace_all(title, "SGT", toupper("Sergeant")), 
         title = str_replace_all(title, " OF ", " ")) %>% ## change director of x to director x 
  fmutate(title = if_else(str_like(title, "DIRECTOR%"), ## change director x to x director. 
                         paste(paste0(str_remove(title, "DIRECTOR")), 
                         paste0("DIRECTOR")), 
                         title
                         ), ## adds an extra space in some cases
          title = str_squish(title),
          title = if_else((title == "PRESIDENTCEO"|
                            title == "PRESIDENTCE"), "PRESIDENT AND CEO", 
                          title ), 
          title = if_else(title == "MD", "PHYSICIAN", title) , 
          title = if_else(str_ends(title, "DIR"), str_replace(title, "DIR", "DIRECTOR"), title),
          # title = if_else(title == "EXECUTIVE DIR", "EXECUTIVE DIRECTOR", title),
          title = if_else(title == "COO", "CHIEF OPERATING OFFICER", title), 
          title = if_else(title == "CFO", "CHIEF FINANCIAL OFFICER", title), 
          title = if_else(title == "CDO", "CHIEF DEVELOPMENT OFFICER", title),
          title = if_else(title == "CPO", "CHIEF PEOPLE OFFCER", title),
          title = if_else(title == "CBO", "CHIEF BUSINESS OFFICER", title),
          title = if_else(title == "CNO", "CHIEF NURSING OFFICER", title),
          title = if_else((title == "SECRETARY TREASURER" |
                            title == "SECRETARY TR"), "SECRETARY AND TREASURER", title), 
          title = if_else(title == "GENERAL MANA", "GENERAL MANAGER", title), 
          title = if_else((title == "PRESIDENT CEO" |
                            title == "CEO AND PRESIDENT"), "PRESIDENT AND CEO", title), 
          title = if_else((title == "EXECUTIVE DIRECTO" |
                            title == "EXECUTIVE DIRECT"), "EXECUTIVE DIRECTOR", title), 
          title = if_else(title == "EXECUTIVE DIRECTORCEO", "EXECUTIVE DIRECTOR", title), 
          title = if_else(str_detect(title, "CHIEF EXECUTIVE OFFICER") &
                            !str_detect(title, "AND"), "EXECUTIVE DIRECTOR", 
                          title), 
          title = if_else(str_detect(title, "CHIEF EXECUTIVE OFFICER") &
                            str_detect(title, "PRESIDENT"), "PRESIDENT AND CEO", 
                          title) 
          ) %>% 
  fmutate(title = str_squish(title)) %>% 
  fsubset(title != "EMPLOYEE" &
            title != "KEY EMPLOYEE" &
            title != "KEY WORKER" &
            title != "SEE SCHEDULE O O AND T TITLES") %>%  ## REMOVE GENERIC TITLES WITH NO VALUE
  fsubset(str_detect(title, "FORMER") == FALSE &
            str_detect(title, "THRU") == FALSE &
            str_detect(title, "THROUGH") == FALSE &
            str_detect(title, "PART YEAR") ==  FALSE) ##EXCLUDE THOSE WHO SERVED ONLY FOR PART OF THE YEAR  

         
  





temp_tbl <- df_comp3 %>% 
                fselect(title) %>% 
                fgroup_by(title) %>%
                fcount(title) %>% 
                fungroup() %>% 
                arrange(desc(N))



DT::datatable(temp_tbl)
                










```

