---
title: "Import data into a flat table"
author: "Mikyas Duga"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE)


library(dplyr)
library(purrr)
library(readr)
library(xml2)
library(stringr)
library(tidyr)

source("my_functions.R")

wd <- "C:/Users/mikyas.duga/OneDrive - BoardSource/IRS data/TY2022"

```

## NOTES

Initial import of part of IRS 2024 xml data. 

```{r}

## read filenames

filenames_01A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_01A"),
    pattern = "*.xml",
    full.names = TRUE
  )


## identify type of return 
library(future)

future::plan(multisession, workers = 4)

Return_info_01A <- furrr::future_map_dfr(filenames_01A, id_pc_2)

Return_info_01A$file_loc <- filenames_01A


saveRDS(Return_info_01A, "data/temp/return_info_01_A.rds")



## 02A

filenames_02A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_02A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_02A <- furrr::future_map(filenames_02A, 
                       get_size)

size_02A <- as_tibble(unlist(size_02A))
which(size_02A$value > 20)


## identify type of return 

Return_info_02A <- furrr::future_map_dfr(filenames_02A[-c(14671, 30236)],
                                         id_pc_2, 
                                         .progress = TRUE )

## excluded 2 very large files. 


XML_too_big <- as.data.frame(filenames_02A[which(size_02A$value > 20)])



Return_info_02A$file_loc <- filenames_02A[-which(size_02A$value > 20)]
## didn't work here
saveRDS(Return_info_02A, "data/temp/return_info_02A.rds")






filenames_03A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_03A"),
    pattern = "*.xml",
    full.names = TRUE
  )



size_03A <- furrr::future_map(filenames_03A, 
                       get_size)

size_03A <- as_tibble(unlist(size_03A))
which(size_03A$value > 20)


Return_info_03A <- furrr::future_map_dfr(filenames_03A,
                                         id_pc_2, 
                                         .progress = TRUE)

Return_info_03A$file_loc <- filenames_03A

saveRDS(Return_info_03A, "data/temp/return_info_03A.rds")


filenames_04A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_04A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_04A <- furrr::future_map(filenames_04A, 
                       get_size)

size_04A <- as_tibble(unlist(size_04A))
which(size_04A$value > 20)


XML_too_big <- rbind.data.frame(
  XML_too_big, 
  filenames_04A[which(size_04A$value > 20)]
                     )  ## add to bix XML list. 


Return_info_04A <- furrr::future_map_dfr(filenames_04A[-which(size_04A$value > 20)],
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_04A$file_loc <- filenames_04A[-which(size_04A$value > 20)]

saveRDS(Return_info_04A, "data/temp/return_info_04A.rds")


## 05A
filenames_05A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_05A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_05A <- furrr::future_map(filenames_05A, 
                       get_size)

size_05A <- as_tibble(unlist(size_05A))
which(size_05A$value > 20)


XML_too_big <- rbind.data.frame(
  XML_too_big,
  filenames_05A[which(size_05A$value > 20)]
                     )  ## add to bix XML list.


Return_info_05A <- furrr::future_map_dfr(filenames_05A[-which(size_05A$value > 20)],
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_05A$file_loc <- filenames_05A[-which(size_05A$value > 20)]
saveRDS(Return_info_05A, "data/temp/return_info_05A.rds")

## 05 B

filenames_05B <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_05B"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_05B <- furrr::future_map(filenames_05B, 
                       get_size)

size_05B <- as_tibble(unlist(size_05B))
which(size_05B$value > 20)


XML_too_big <- rbind.data.frame(
  XML_too_big,
  filenames_05B[which(size_05B$value > 20)]
                     )  ## add to bix XML list.


Return_info_05B <- furrr::future_map_dfr(filenames_05B[-which(size_05B$value > 20)],
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_05B$file_loc <- filenames_05B[-which(size_05B$value > 20)]
saveRDS(Return_info_05B, "data/temp/return_info_05B.rds")


saveRDS(XML_too_big, "data/temp/xml_too_big.rds")

## 06A

filenames_06A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_06A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_06A <- furrr::future_map(filenames_06A, 
                       get_size)

size_06A <- as_tibble(unlist(size_06A))
which(size_06A$value > 20)


# XML_too_big <- rbind.data.frame(
#   XML_too_big,
#   filenames_06A[which(size_06A$value > 20)]
#                      )  ## add to bix XML list.


Return_info_06A <- furrr::future_map_dfr(filenames_06A,
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_06A$file_loc <- filenames_06A
saveRDS(Return_info_06A, "data/temp/return_info_06A.rds")


## 07A
filenames_07A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_07A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_07A <- furrr::future_map(filenames_07A, 
                       get_size)

size_07A <- as_tibble(unlist(size_07A))
which(size_07A$value > 20)


# XML_too_big <- rbind.data.frame(
#   XML_too_big,
#   filenames_07A[which(size_07A$value > 20)]
#                      )  ## add to bix XML list.


Return_info_07A <- furrr::future_map_dfr(filenames_07A,
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_07A$file_loc <- filenames_07A
saveRDS(Return_info_07A, "data/temp/return_info_07A.rds")



## 08A
filenames_08A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_08A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_08A <- furrr::future_map(filenames_08A, 
                       get_size)

size_08A <- as_tibble(unlist(size_08A))
which(size_08A$value > 20)


# XML_too_big <- rbind.data.frame(
#   XML_too_big,
#   filenames_08A[which(size_08A$value > 20)]
#                      )  ## add to bix XML list.


Return_info_08A <- furrr::future_map_dfr(filenames_08A,
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_08A$file_loc <- filenames_08A
saveRDS(Return_info_08A, "data/temp/return_info_08A.rds")



## 09A

filenames_09A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_09A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_09A <- furrr::future_map(filenames_09A, 
                       get_size)

size_09A <- as_tibble(unlist(size_09A))
which(size_09A$value > 20)


# XML_too_big <- rbind.data.frame(
#   XML_too_big,
#   filenames_09A[which(size_09A$value > 20)]
#                      )  ## add to bix XML list.


Return_info_09A <- furrr::future_map_dfr(filenames_09A,
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_09A$file_loc <- filenames_09A
saveRDS(Return_info_09A, "data/temp/return_info_09A.rds")



## 10A

filenames_10A <-
  list.files(
   paste0(wd, "/2024_TEOS_XML_10A"),
    pattern = "*.xml",
    full.names = TRUE
  )


size_10A <- furrr::future_map(filenames_10A, 
                       get_size)

size_10A <- as_tibble(unlist(size_10A))
which(size_10A$value > 20)


# XML_too_big <- rbind.data.frame(
#   XML_too_big,
#   filenames_10A[which(size_10A$value > 20)]
#                      )  ## add to bix XML list.


Return_info_10A <- furrr::future_map_dfr(filenames_10A,
                                         id_pc_2, 
                                         .progress = TRUE)


Return_info_10A$file_loc <- filenames_10A
saveRDS(Return_info_10A, "data/temp/return_info_10A.rds")






# future::plan(multisession, workers = 4)
# 
# ## 01A
# df_ind_comp_01A <- future_map(read_rds("data/pc_list_01A.rds"), 
#                          ext_ind_comp, 
#                          .progress = TRUE)

# 202431589349300203_public -- PC
# 202401459339300300_public -- 990T
# 202401459349100020_public -- PF 


## 202401459349100025_public in 06A is a PF with schedule B not required. 



test1 <- "C:/Users/mikyas.duga/OneDrive - BoardSource/IRS data/TY2022/2024_TEOS_XML_06A/202431589349300203_public.xml"


a <- pf_ext_ind_comp(test1)

dat <- read_xml(test1)

  xml_ns_strip(dat)

  xml_text((xml_find_first(dat, "//ReturnHeader/ReturnTypeCd")))

xml_text(xml_find_first(dat, "//ReturnHeader/Filer/USAddress/AddressLine1Txt"))

xml_text(xml_find_all(dat, "//ReturnData/IRS990/Form990PartVIISectionAGrp/PersonNm"))



xml_text(xml_find_all(dat,
                      
"//ReturnData/IRS990/Organization501cInd"))


xml_text(xml_find_all(dat,
                      
'//ReturnData/IRS990/Organization501cInd'))




xml_text(xml_find_all(dat,
                      
"//ReturnData/IRS990PF/AnalysisOfRevenueAndExpenses/ScheduleBNotRequiredInd"))



xml_text(xml_find_all(dat,
                      
"//ReturnData/IRS990PF/FMVAssetsEOYAmt"))


xml_text(xml_find_all(dat,
                      
"//ReturnData/IRS990PF/Form990PFBalanceSheetsGrp/TotalAssetsEOYAmt"))








```

## Test functions
```{r}
info_04A <- read_rds("data/temp/return_info_04A.rds")

set.seed(12182024)

sample <- info_04A %>% 
  filter(ret_type == "990" |
           ret_type == "990PF") %>% 
  slice_sample(n = 100, replace = FALSE)


library(future)

plan(multisession, workers = 4)

pc_which <- which(sample$ret_type == "990")



df_pc <- furrr::future_map(sample$file_loc[pc_which], ext_ind_comp)













```

